Sharpshooter/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sharpshooter.Models
{
    public class Menu
    {
        [Key]
        public int MenuID { get; set; }

        [Display(Name ="Menu Title")]
        public string MenuTitle { get; set; }

        [Display(Name ="Description")]
        public string MenuDescription { get; set; }

        [Display(Name ="Menu Image")]
        public string MenuImg { get; set; }

        public virtual List<MenuItem> MenuItems { get; set; }

        public virtual List<MenuGroup> MenuGroups { get; set; }
    }
}

Sharpshooter/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;

namespace Sharpshooter.Controllers
{
    public class MenusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menus
        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        } 

        public ActionResult Menu()
        {
            var categories = db.Menus.ToList();
            return View(categories);
        }

        public ActionResult ViewMenuAll()
        {
            var categories = db.Menus.ToList();
            return View(categories);
        }


        public ActionResult Browse(string category)
        {
            var categoryModel = db.Menus.Include("MenuItems").Single(c => c.MenuTitle == category);
            return View(categoryModel);
            
        }
        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        public ActionResult ViewItems(int id)
        {
            MenuItem menuItem = new MenuItem();
            menuItem = db.MenuItems.Where(x => x.MenuItemID == id).FirstOrDefault();
            
            return View(menuItem);
        }

        public ActionResult ViewMenu(int id)
        {
            var Item = db.MenuItems.Find(id);
            return View(Item);
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuID,MenuTitle,MenuDescription,MenuImg")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuID,MenuTitle,MenuDescription,MenuImg")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menus.Find(id);
            db.Menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult MenuReview(int? id)
        {
            Review review = new Review();
            review = db.Reviews.Where(x => x.MenuItemID == id).FirstOrDefault();
            return PartialView("MenuReview", db.Reviews.Where(x => x.MenuItemID == id).ToList());
        }
        public ActionResult CalcAvg(int? id)
        {
            int num = 0;
            float Average = 0;
            Review review = new Review();
            review = db.Reviews.Where(x => x.MenuItemID == id).FirstOrDefault();
            foreach (var i in db.Reviews.Where(x => x.MenuItemID == id).ToList())
            {
                Average = (Average + review.Rating);
                num = num + 1;
            }
            Average = Average / num;

            return View(Average);

        }
    }
}

Sharpshooter/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;

namespace Sharpshooter.Controllers
{
    public class ReviewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reviews
        public ActionResult Index()
        {
            var reviews = db.Reviews.Include(r => r.MenuItem);
            return View(reviews.ToList());
        }

        public ActionResult ViewReview(string searchBy, string search)
        {
           
                return View(db.Reviews.Where(x => x.UserName.StartsWith(search) || search == null).ToList());
           
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // GET: Reviews/Create
        public ActionResult Create()
        {
            ViewBag.MenuItemID = new SelectList(db.MenuItems, "MenuItemID", "MenuItemTitle");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReviewId,MenuItemID,UserName,ReviewOfItem,Rating,StarRating")] Review review)
        {
            if (ModelState.IsValid)
            {

                review.Rating = review.GetRatingNumb();

                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("ViewReview");
            }

            ViewBag.MenuItemID = new SelectList(db.MenuItems, "MenuItemID", "MenuItemTitle", review.MenuItemID);
            return View(review);
        }

        // GET: Reviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuItemID = new SelectList(db.MenuItems, "MenuItemID", "MenuItemTitle", review.MenuItemID);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReviewId,MenuItemID,UserName,ReviewOfItem,Rating,StarRating")] Review review)
        {
            if (ModelState.IsValid)
            {

                review.Rating = review.GetRatingNumb();

                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuItemID = new SelectList(db.MenuItems, "MenuItemID", "MenuItemTitle", review.MenuItemID);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharpshooter/Views/Menus/Browse.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Browse";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}
<style>
    div {
        text-align: center;
        align-content: center;
    }

    img {
        border-radius: 10px;
    }
</style>
<div> <h2 style="margin:auto"><em>@Model.MenuTitle</em></h2></div>
<div>
    <ul style="margin:auto">
        @foreach (var item in Model.MenuItems)
        {
        <div class="blog-box">
            <li>
                <h3>@item.MenuItemTitle</h3>
                <a href="@Url.Action("ViewItems", new { id = item.MenuItemID})">
                    <img border="0" alt="" src="@Url.Content(item.MenuItemImg)" width="400" height="300">
                </a>
            </li>
        </div>
        <br />

        }
    </ul>
</div>

<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/Menus/Create.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Menu</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MenuTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MenuTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MenuTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MenuImg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MenuImg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MenuImg, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MenuDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MenuDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MenuDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/Menus/Delete.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuImg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuImg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuDescription)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>



<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/Menus/Details.cshtml
@model Sharpshooter.Models.Menu

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Menu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuImg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuImg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MenuID }) |
    @Html.ActionLink("Back to List", "Index")
</p>




<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/Menus/Index.cshtml
@model IEnumerable<Sharpshooter.Models.Menu>

@{
    ViewBag.Title = "Admin Menu";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Admin Menu</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MenuTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuImg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuDescription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MenuTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MenuImg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MenuDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.MenuID }) |
            @Html.ActionLink("Details", "Details", new { id = item.MenuID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.MenuID }) |
            @*@Html.ActionLink("View Menu", "ViewMenu", new { id = item.MenuID })*@
            @Html.ActionLink("View Menu", "ViewMenuAll", "Menus")
        </td>
    </tr>
    }

</table>

<br /><br />

<p>
    <li>&bull;@Html.ActionLink(" Menu Groups", "Index", "MenuGroups")</li>
</p>



<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/Menus/ViewItems.cshtml
@model Sharpshooter.Models.MenuItem

@{
    ViewBag.Title = "Item - " + Model.MenuItemTitle;
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<style>
    p {
        align-content: center;
        text-align: center
    }

    div {
        margin-left: auto;
    }

    img {
        border-radius: 10px;
    }

    .checked {
        color: orange;
    }
</style>

<p>
    @Html.ActionLink("Back to Full Menu", "ViewMenuAll")
</p>


<body>


    <!-- Start Shop Detail  -->
    <div class="shop-detail-box-main">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-6">
                    <div id="carousel-example-1" class="single-product-slider carousel slide" data-ride="carousel">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active"> <img class="d-block w-100" src="@Url.Content(Model.MenuItemImg)" alt="First slide"> </div>
                        </div>
                        <a class="carousel-control-prev" href="#carousel-example-1" role="button" data-slide="prev">
                            <i class="fa fa-angle-left" aria-hidden="true"></i>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-example-1" role="button" data-slide="next">
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                            <span class="sr-only">Next</span>
                        </a>
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-1" data-slide-to="0" class="active">
                                <img class="d-block w-100 img-fluid" src="@Url.Content(Model.MenuItemImg)" alt="" />
                            </li>
                            <li data-target="#carousel-example-1" data-slide-to="1">
                                <img class="d-block w-100 img-fluid" src="@Url.Content(Model.MenuItemImg)" alt="" />
                            </li>
                            <li data-target="#carousel-example-1" data-slide-to="2">
                                <img class="d-block w-100 img-fluid" src="@Url.Content(Model.MenuItemImg)" alt="" />
                            </li>
                        </ol>
                    </div>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-6">
                    <div class="single-product-details">
                        <h2>@Model.MenuItemTitle</h2>
                        <h5>R @String.Format("{0:F}", Model.MenuItemCost)</h5>

                        <p>
                            <h4>Food Item Description:</h4>
                        <p>
                            @Model.MenuItemDescription
                        </p>

                        <p>
                            <h4>Food Item Ingredients:</h4>
                        <p>
                            @Model.MenuItemIngredients
                        </p>

                        <div class="price-box-bar">
                            <div class="cart-and-bay-btn">
                                <a class="btn hvr-hover" data-fancybox-close="" href="../ViewMenuAll">Back To Menu</a>
                                <a class="btn hvr-hover" data-fancybox-close="" @Html.ActionLink("Add To Cart", "AddToCart", "ShoppingCart")</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <br /><br />
            <br /><br />

                  <div class="add-to-btn">


                      @if (User.IsInRole("Customer"))
                      {
                          <div class="add-comp">
                              <a class="btn hvr-hover" href=@Url.Action("Create","Reviews", new { id = Model.MenuItemID }, "") ><i class="fas fa-star"></i> Add Review</a>
                          </div>
                      }



                      <div class="cell">
                          @{ Html.RenderAction("MenuReview");}
                      </div>

                      <br />

                      <div class="row my-5">
                          <div class="col-lg-12">
                              <div class="title-all text-center">
                                  <h1>Featured Products</h1>
                                  <p>All of Our Tasty Menus to look at !!!</p>
                              </div>
                              <div class="featured-products-box owl-carousel owl-theme">
                                  <div class="item">
                                      <div class="products-single fix">
                                          <div class="box-img-hover">
                                              <img src="~/Content/ItemImages/Breyani.jpg" class="img-fluid" alt="Image">
                                              <div class="mask-icon">
                                                  <ul>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                  </ul>
                                                  <a class="cart" href="@Url.Action("ViewMenuAll", "Menus")">View</a>
                                              </div>
                                          </div>
                                          <div class="why-text">
                                              <h4>Breyani</h4>
                                              <h5> Give it a Try</h5>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="item">
                                      <div class="products-single fix">
                                          <div class="box-img-hover">
                                              <img src="~/Content/ItemImages/Chicken Curry and Rice.jpg" class="img-fluid" alt="Image">
                                              <div class="mask-icon">
                                                  <ul>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                  </ul>
                                                  <a class="cart" href="@Url.Action("ViewMenuAll", "Menus")">View</a>
                                              </div>
                                          </div>
                                          <div class="why-text">
                                              <h4>Curries</h4>
                                              <h5> Give it a Try</h5>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="item">
                                      <div class="products-single fix">
                                          <div class="box-img-hover">
                                              <img src="~/Content/ItemImages/Double Cheeseburger.jpg" class="img-fluid" alt="Image">
                                              <div class="mask-icon">
                                                  <ul>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                  </ul>
                                                  <a class="cart" href="@Url.Action("ViewMenuAll", "Menus")">View</a>
                                              </div>
                                          </div>
                                          <div class="why-text">
                                              <h4>Burgers</h4>
                                              <h5> Give it a Try</h5>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="item">
                                      <div class="products-single fix">
                                          <div class="box-img-hover">
                                              <img src="~/Content/ItemImages/Samoosa.jpg" class="img-fluid" alt="Image">
                                              <div class="mask-icon">
                                                  <ul>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                  </ul>
                                                  <a class="cart" href="@Url.Action("ViewMenuAll", "Menus")">View</a>
                                              </div>
                                          </div>
                                          <div class="why-text">
                                              <h4>Starters</h4>
                                              <h5> Give it a Try</h5>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="item">
                                      <div class="products-single fix">
                                          <div class="box-img-hover">
                                              <img src="~/Content/ItemImages/Mutton Bunny Chow.jpg" class="img-fluid" alt="Image">
                                              <div class="mask-icon">
                                                  <ul>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                      <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                  </ul>
                                                  <a class="cart" href="@Url.Action("ViewMenuAll", "Menus")">View</a>
                                              </div>
                                          </div>
                                          <div class="why-text">
                                              <h4>Bunnies</h4>
                                              <h5> Give it a Try</h5>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>

                  </div>
        </div>
    <!-- End Cart -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

    <!-- ALL JS FILES -->
    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- ALL PLUGINS -->
    <script src="~/Content/js/jquery.superslides.min.js"></script>
    <script src="~/Content/js/bootstrap-select.js"></script>
    <script src="~/Content/js/inewsticker.js"></script>
    <script src="~/Content/js/bootsnav.js."></script>
    <script src="~/Content/js/images-loded.min.js"></script>
    <script src="~/Content/js/isotope.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/baguetteBox.min.js"></script>
    <script src="~/Content/js/form-validator.min.js"></script>
    <script src="~/Content/js/contact-form-script.js"></script>
    <script src="~/Content/js/custom.js"></script>
</body>

</html>


<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/Menus/ViewMenu.cshtml
@model IEnumerable<Sharpshooter.Models.Menu>

@{
    ViewBag.Title = "ViewMenu";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Browse Category</h2>
<p>
    Select from @Model.Count()
    genres:
</p>
<ul style="margin-left:45px">
    @foreach (var category in Model)
    {
        <li>@Html.ActionLink(category.MenuTitle, "Browse", new { category = category.MenuTitle })</li>
    }
</ul>


<br /><br /><br /><br />
<br /><br /><br /><br />