Sharpshooter/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sharpshooter.Models
{
    public class MenuItem
    {
        public int MenuItemID { get; set; }

        [ForeignKey("Menu")]
        public int MenuID { get; set; }
        public virtual Menu Menu { get; set; }

        [ForeignKey("MenuGroup")]
        public int MenuGroupID { get; set; }
        public virtual MenuGroup MenuGroup { get; set; }

        public virtual List<OrderDetail> OrderDetails { get; set; }

        public virtual List<Review> Review { get; set; }



        [Required(ErrorMessage ="A title is required for the menu item")]
        [Display(Name ="Item Name")]
        public string MenuItemTitle { get; set; }

        [Display(Name ="Description")]
        public string MenuItemDescription { get; set; }

        [Display(Name = "Nutrition Information")]
        public string MenuItemNutrition { get; set; }

        [Display(Name = "Information about Ingredients")]
        public string MenuItemIngredients { get; set; }

        [Display(Name ="How many in serving")]
        public int MenuItemQuantity { get; set; }

        [Display(Name ="Food Image")]
        public string MenuItemImg { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }


        [Display(Name ="Cost Of Menu Item")]
        public decimal MenuItemCost { get; set; }

    }
}

Sharpshooter/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;
using System.IO;

namespace Sharpshooter.Controllers
{
    public class MenuItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MenuItems
        public ActionResult Index()
        {
            var menuItems = db.MenuItems.Include(m => m.Menu).Include(m => m.MenuGroup);
            return View(menuItems.ToList());
        }


        public ActionResult ViewMenuItems()
        {
            var menuItems = db.MenuItems.Include(m => m.Menu).Include(m => m.MenuGroup);
            return View(menuItems.ToList());
        }

        // GET: MenuItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = db.MenuItems.Find(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            return View(menuItem);
        }

        // GET: MenuItems/Create
        public ActionResult Create()
        {
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle");
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle");
            return View();
        }

        // POST: MenuItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuItemID,MenuID,MenuGroupID,MenuItemTitle,MenuItemDescription,MenuItemNutrition,MenuItemIngredients,MenuItemQuantity,MenuItemImg,ImageFile,MenuItemCost")] MenuItem menuItem/*, HttpPostedFileBase MenuItemImg*/)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(menuItem.ImageFile.FileName);
                string extension = Path.GetExtension(menuItem.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                menuItem.MenuItemImg = "~/Content/ItemImages/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/ItemImages/"), fileName);
                menuItem.ImageFile.SaveAs(fileName);



                //MenuItem m = new MenuItem();
                //m.MenuItemTitle = menuItem.MenuItemTitle;
                //m.MenuItemImg = MenuItemImg.FileName.ToString();

                //var path = Server.MapPath("~/Content/ItemImages/");
                //MenuItemImg.SaveAs(Path.Combine(path, MenuItemImg.FileName.ToString()));

                db.MenuItems.Add(menuItem);
                db.SaveChanges();
                return RedirectToAction("Items", "Admin");
            }

            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuItem.MenuID);
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle", menuItem.MenuGroupID);
            return View(menuItem);
        }

        // GET: MenuItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = db.MenuItems.Find(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuItem.MenuID);
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle", menuItem.MenuGroupID);
            return View(menuItem);
        }

        // POST: MenuItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuItemID,MenuID,MenuGroupID,MenuItemTitle,MenuItemDescription,MenuItemNutrition,MenuItemIngredients,MenuItemQuantity,MenuItemImg,ImageFile,MenuItemCost")] MenuItem menuItem)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(menuItem.ImageFile.FileName);
                string extension = Path.GetExtension(menuItem.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                menuItem.MenuItemImg = "~/Content/ItemImages/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/ItemImages/"), fileName);
                menuItem.ImageFile.SaveAs(fileName);


                db.Entry(menuItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuID = new SelectList(db.Menus, "MenuID", "MenuTitle", menuItem.MenuID);
            ViewBag.MenuGroupID = new SelectList(db.MenuGroups, "MenuGroupID", "MenuGroupTitle", menuItem.MenuGroupID);
            return View(menuItem);
        }

        // GET: MenuItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuItem menuItem = db.MenuItems.Find(id);
            if (menuItem == null)
            {
                return HttpNotFound();
            }
            return View(menuItem);
        }

        // POST: MenuItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MenuItem menuItem = db.MenuItems.Find(id);
            db.MenuItems.Remove(menuItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




    }
}

Sharpshooter/Views/MenuItems/Create.cshtml
@model Sharpshooter.Models.MenuItem

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "MenuItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MenuItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuGroupID, "MenuGroupID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuGroupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemNutrition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemNutrition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemNutrition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemIngredients, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemIngredients, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemIngredients, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemQuantity, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" class="form-control" required />
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}





<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/MenuItems/Delete.cshtml
@model Sharpshooter.Models.MenuItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MenuItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuGroup.MenuGroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuGroup.MenuGroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemNutrition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemNutrition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemIngredients)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemIngredients)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.MenuItemQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemImg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemImg)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemCost)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>



<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/MenuItems/Details.cshtml
@model Sharpshooter.Models.MenuItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MenuItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.MenuTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuGroup.MenuGroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuGroup.MenuGroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemNutrition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemNutrition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemIngredients)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemIngredients)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.MenuItemQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemImg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemImg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenuItemCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuItemCost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MenuItemID }) |
    @Html.ActionLink("Back to List", "Index")
</p>




<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/MenuItems/Edit.cshtml
@model Sharpshooter.Models.MenuItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "MenuItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MenuItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MenuItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.MenuID, "MenuID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuGroupID, "MenuGroupID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MenuGroupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemNutrition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemNutrition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemNutrition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemIngredients, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemIngredients, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemIngredients, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemQuantity, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" class="form-control" required />
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MenuItemCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuItemCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuItemCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}




<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/MenuItems/Index.cshtml
@model IEnumerable<Sharpshooter.Models.MenuItem>

@{
    ViewBag.Title = "Admin Menu Items";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Admin Menu Items</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuGroup.MenuGroupTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemNutrition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemIngredients)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.MenuItemQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemImg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemCost)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Menu.MenuTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuGroup.MenuGroupTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemNutrition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemIngredients)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.MenuItemQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemImg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemCost)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MenuItemID }) |
                @Html.ActionLink("Details", "Details", new { id = item.MenuItemID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MenuItemID }) |
            </td>
        </tr>
    }

</table>



<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />

Sharpshooter/Views/MenuItems/ViewMenuItems.cshtml
@model IEnumerable<Sharpshooter.Models.MenuItem>

@{
    ViewBag.Title = "Menu Items";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Menu Items</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Menu.MenuTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuGroup.MenuGroupTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemNutrition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemIngredients)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MenuItemCost)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Menu.MenuTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuGroup.MenuGroupTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemNutrition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemIngredients)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MenuItemCost)
            </td>

        </tr>
    }

</table>


<br /><br /><br /><br />
<br /><br /><br /><br />
<br /><br /><br /><br />