Sharpshooter/Controllers/AdminInventoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Sharpshooter.Models;

namespace Sharpshooter.Controllers
{
    public class AdminInventoriesController : Controller
    {
        //email code
        public ActionResult SendEmail()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendEmail(string receiver, string subject, string message)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ViewBag.Success = "Success, Email has been sent";
                    var senderEmail = new MailAddress("taslyn.moopanar@gmail.com", "Employee");
                    var receiverEmail = new MailAddress("tasmoop@gmail.com", "Receiver");
                    var password = "T@slyn2968";
                    var sub = subject;
                    var body = message;
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.gmail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(senderEmail.Address, password)
                    };
                    using (var mess = new MailMessage(senderEmail, receiverEmail)
                    {
                        Subject = subject,
                        Body = body
                    })
                    {
                        smtp.Send(mess);
                    }
                    return View();
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Error";
            }
            return View();
        }



        private ApplicationDbContext db = new ApplicationDbContext();


        //sorting code
        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_asc" : "";
            ViewBag.QuantityRemainingSortParm = sortOrder == "QuantityRemaining" ? "quantityRemaining_asc" : "QuantityRemaining";

            var inventory = from s in db.Inventories
                            select s;

            //search function
            if (!String.IsNullOrEmpty(searchString))
            {
                inventory = inventory.Where(s => s.Name.Contains(searchString));

            }

            





            switch (sortOrder)
            {
                case "name_asc":
                    inventory = inventory.OrderByDescending(s => s.Name);
                    break;
                case "Type":
                    inventory = inventory.OrderBy(s => s.Type);
                    break;
                case "quantityRemaining_asc":
                    inventory = inventory.OrderBy(s => s.QuantityRemaining);
                    break;

                default:
                    inventory = inventory.OrderBy(s => s.Name);
                    break;
            }
            return View(inventory.ToList());
        }


        //low stock code
        public ViewResult lowStock(string sortOrder, string searchString)
        {
            var inventory = from s in db.Inventories
                            select s;

            return View(inventory.Where(i => (i.Name.Equals("Fanta") && i.QuantityRemaining < 10) ||
            (i.Name.Equals("Mutton") && i.QuantityRemaining < 30) ||
            (i.Name.Equals("Beans") && i.QuantityRemaining < 40) ||
            (i.Name.Equals("Chicken") && i.QuantityRemaining < 30) || 
            (i.Name.Equals("Creme soda") && i.QuantityRemaining < 10) ||
             (i.Name.Equals("Bread") && i.QuantityRemaining < 13) ||
            (i.Name.Equals("Carrots") && i.QuantityRemaining < 15) || 
            (i.Name.Equals("Milk") && i.QuantityRemaining < 5) ||
            (i.Name.Equals("Onion") && i.QuantityRemaining < 10) || 
            (i.Name.Equals("Tomatoe") && i.QuantityRemaining < 15) || 
            (i.Name.Equals("Potatoe") && i.QuantityRemaining < 15) ||
            (i.Name.Equals("Roti") && i.QuantityRemaining < 20)));
        }



        // GET: Inventories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // GET: Inventories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Type,QuantityRemaining,PricePerUnit")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                db.Inventories.Add(inventory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inventory);
        }

        // GET: Inventories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // POST: Inventories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Type,QuantityRemaining,PricePerUnit")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inventory);
        }

        // GET: Inventories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // POST: Inventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Inventory inventory = db.Inventories.Find(id);
            db.Inventories.Remove(inventory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharpshooter/Views/AdminInventories/Create.cshtml
@model Sharpshooter.Models.Inventory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inventory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityRemaining, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityRemaining, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityRemaining, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Sharpshooter/Views/AdminInventories/Delete.cshtml
@model Sharpshooter.Models.Inventory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuantityRemaining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuantityRemaining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerUnit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sharpshooter/Views/AdminInventories/Details.cshtml
@model Sharpshooter.Models.Inventory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuantityRemaining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuantityRemaining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerUnit)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sharpshooter/Views/AdminInventories/Edit.cshtml
@model Sharpshooter.Models.Inventory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/TempLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inventory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityRemaining, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityRemaining, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityRemaining, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Sharpshooter/Views/AdminInventories/Index.cshtml
@model IEnumerable<Sharpshooter.Models.Inventory>

@{ ViewBag.Title = "Index";
    Layout = "~/Views/Shared/TempLayout.cshtml"; }


<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>STOCK INVENTORY</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">STOCK INVENTORY</li>
                </ul>
            </div>
        </div>
    </div>
</div>


<br /><br />

<h2 class="noo-sh-title">Stock Inventory</h2>

<br />


@using (Html.BeginForm())
{
    <span style="text-align: right">
        <p>
            Find by name: @Html.TextBox("SearchString")
            <input type="submit" value="Search" />
        </p>
    </span>
}

<p>
    @*@Html.ActionLink("View Low Stock", "lowStock")*@
    <input type="button" value="View Low Stock" onclick="location.href='@Url.Action("lowStock", "AdminInventories")'" /> <input type="button" value="Email Supplier" onclick="location.href='@Url.Action("SendEmail", "AdminInventories")'" />
</p>



<span style="text-align: right">
    <p>
        @Html.ActionLink("Add New Item", "Create")
        @*<input type="button" value="Add New Item" onclick="location.href='@Url.Action("Create", "Inventories")'" />*@
    </p>
</span>



<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            Type
        </th>
        <th>
            @Html.ActionLink("QuantityRemaining", "Index", new { sortOrder = ViewBag.QuantityRemainingSortParm })
        </th>
        <th>
            UnitPrice
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantityRemaining)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PricePerUnit)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Sharpshooter/Views/AdminInventories/SendEmail.cshtml
@{ ViewBag.Title = "SendEmail"; }


<h2 class="noo-sh-title">Send Email</h2>

@if (ViewBag.Success != null)
{<h2> @ViewBag.Success </h2>} <form method="post"
                                    action="SendEmail">
    <div class="container">
        <span class="form-control-static"> Receiver: </span> <input class="form-control"
                                                                    type="text"
                                                                    name="receiver" /> <br /> <span class="form-control-static"> Subject: </span> <input class="form-control"
                                                                                                                                                         type="text"
                                                                                                                                                         name="subject" /> <br /> <span class="form-control-static"> Message: </span> <input class="form-control"
                                                                                                                                                                                                                                             type="text"
                                                                                                                                                                                                                                             name="message" /> <br /> <input class="btn btn-primary"
                                                                                                                                                                                                                                                                             type="submit"
                                                                                                                                                                                                                                                                             value="Send" />
    </div>
</form>
@Html.ActionLink("Return to Inventory ", "Index")

Sharpshooter/Views/AdminInventories/lowStock.cshtml
@model IEnumerable<Sharpshooter.Models.Inventory>
@{ ViewBag.Title = "lowStock";
    Layout = "~/Views/Shared/TempLayout.cshtml"; }





<table class="table">


    <h2 class="noo-sh-title">Low Stock Inventory</h2>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantityRemaining)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PricePerUnit)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>*@





        </tr>
    }

</table>
@Html.ActionLink("Return to Inventory ", "Index")